### ISSUE TITLE
picture of the detected puncta in the output

### ISSUE THREAD

**Issue by matwgmkw** [stjude/punctatools#27]
Hi. Thanks for developing this package. Is it possible to add pictures of the detected puncta in the output? Something similar to the picture below as in the setup stage but for all the analyzed pictures:

<img width="376" alt="Screenshot 2022-09-29 at 10 52 37 PM" src="https://user-images.githubusercontent.com/66743492/193199973-9b517cf5-4379-4317-9a6e-7279d409a543.png">

I think that should help us to know whether the analysis is good or not. Also, is there a way to calibrate the scale (how many pixel = how many micron)? I noticed that the volumes in the output files are too big and not seem to be correct.

Thank you.

Matthew

**Comment by amedyukhina** [comment]
Hi Matthew, 

the pipeline generates a folder with segmented images ("puncta_segm"), where the original images are combined with segmented masks for nuclei and puncta. You can open these images with Fiji, and overlay segmented masks onto the original images when needed. The masks are provided as extra channels, with a unique intensity value for each object - these values correspond to puncta and ROI IDs from the output quantification files.

Regarding the scale, this information is loaded from the image files. There isn't currently any way to set this, except if you compile image stacks from individual z-layers and channels with the "setup_images_to_stack" and "run_images_to_stack" notebooks. But you have a point: it would be nice to have the option to edit voxel size information in already combined tiff stacks. 

I am adding this to my ToDo list. For now, you can try to change the voxel size / scale information in Fiji (Image Properties). It should be relatively straightforward to create a macro that would change voxel size in all your images.

Cheers,
Anna
